# https://docs.microsoft.com/azure/devops/pipelines/languages/python
pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'
    
- bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
  displayName: Add conda to PATH

- bash: conda create --yes --quiet --name myEnvironment python=$PYTHON_VERSION # [other packages ...]
  displayName: Create Anaconda environment

- script: python helloworld.py
